### ISSUE TITLE
Add option to update draft (or republish)

### ISSUE THREAD

**Issue by cherryramatisdev** [zoedsoupe/devit#1]
Today every time we call devit with `-p` it uploads a new instance of the article, maybe we could enable some option to update the content of a article

Something like:

```sh
devit -u ./path
devit --update ./path
```

> Disclaimer: I don't know if dev.to API has support for this

**Comment by zoedsoupe** [comment]
hmm interesting proposal! I’ll check the Dev to API as when I built this package wasn’t possible to update an already published post. Altough was possible to “publish” as a draft and then publish.

**Comment by cherryramatisdev** [comment]
Yeah, I've been looking into the API recently to implement this route.

In the worst-case scenario, we can maybe do the following:

- **Only for drafts** we enable the `--update` flag, which deletes the article and republishes it.

I'll continue looking into more details for the dev.to API, if this it's not possible you find it acceptable to have the option I provided above?

If it's ok I can make a PR for that.

**Comment by zoedsoupe** [comment]
that sounds awesome! of course I accept this feature! I already got stucked in this scenario where I wanted to edit a typo on my post and then I needed to go to their website, find my post and finally edit it… this feature is a must-have!

**Comment by cherryramatisdev** [comment]
Yeah me too lol

Specially when I need to produce Table of contents

**Comment by cherryramatisdev** [comment]
Probably it's not possible because there is no route to delete an article yet

We're bound to this issue I think: https://github.com/forem/forem/issues/17039

I'll investigate more on this matter
